// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fbs.proto

#include "fbs.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace fbs {
class BizDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BizData>
      _instance;
} _BizData_default_instance_;
}  // namespace fbs
namespace protobuf_fbs_2eproto {
static void InitDefaultsBizData() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fbs::_BizData_default_instance_;
    new (ptr) ::fbs::BizData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fbs::BizData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BizData =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBizData}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_BizData.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fbs::BizData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fbs::BizData, bytedata_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::fbs::BizData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::fbs::_BizData_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "fbs.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\tfbs.proto\022\003fbs\"\033\n\007BizData\022\020\n\010byteData\030"
      "\001 \001(\01429\n\007BizPipe\022.\n\nonBusiness\022\014.fbs.Biz"
      "Data\032\014.fbs.BizData\"\000(\0010\001B(\n\024io.grpc.reck"
      "less.fbsB\010FbsProtoP\001\242\002\003HLWb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 154);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "fbs.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_fbs_2eproto
namespace fbs {

// ===================================================================

void BizData::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BizData::kByteDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BizData::BizData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_fbs_2eproto::scc_info_BizData.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:fbs.BizData)
}
BizData::BizData(const BizData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  bytedata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bytedata().size() > 0) {
    bytedata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bytedata_);
  }
  // @@protoc_insertion_point(copy_constructor:fbs.BizData)
}

void BizData::SharedCtor() {
  bytedata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

BizData::~BizData() {
  // @@protoc_insertion_point(destructor:fbs.BizData)
  SharedDtor();
}

void BizData::SharedDtor() {
  bytedata_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void BizData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BizData::descriptor() {
  ::protobuf_fbs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fbs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BizData& BizData::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_fbs_2eproto::scc_info_BizData.base);
  return *internal_default_instance();
}


void BizData::Clear() {
// @@protoc_insertion_point(message_clear_start:fbs.BizData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bytedata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool BizData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fbs.BizData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes byteData = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_bytedata()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fbs.BizData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fbs.BizData)
  return false;
#undef DO_
}

void BizData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fbs.BizData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes byteData = 1;
  if (this->bytedata().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->bytedata(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:fbs.BizData)
}

::google::protobuf::uint8* BizData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:fbs.BizData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes byteData = 1;
  if (this->bytedata().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->bytedata(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fbs.BizData)
  return target;
}

size_t BizData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fbs.BizData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes byteData = 1;
  if (this->bytedata().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->bytedata());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BizData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fbs.BizData)
  GOOGLE_DCHECK_NE(&from, this);
  const BizData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BizData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fbs.BizData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fbs.BizData)
    MergeFrom(*source);
  }
}

void BizData::MergeFrom(const BizData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fbs.BizData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.bytedata().size() > 0) {

    bytedata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bytedata_);
  }
}

void BizData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fbs.BizData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BizData::CopyFrom(const BizData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fbs.BizData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BizData::IsInitialized() const {
  return true;
}

void BizData::Swap(BizData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BizData::InternalSwap(BizData* other) {
  using std::swap;
  bytedata_.Swap(&other->bytedata_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata BizData::GetMetadata() const {
  protobuf_fbs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fbs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace fbs
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::fbs::BizData* Arena::CreateMaybeMessage< ::fbs::BizData >(Arena* arena) {
  return Arena::CreateInternal< ::fbs::BizData >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
