// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fbs.proto
// Original file comments:
// protoc --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` ./fbs.proto
// protoc --cpp_out=. ./fbsproto
//
#ifndef GRPC_fbs_2eproto__INCLUDED
#define GRPC_fbs_2eproto__INCLUDED

#include "fbs.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace fbs {

class BizPipe final {
 public:
  static constexpr char const* service_full_name() {
    return "fbs.BizPipe";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::fbs::BizData, ::fbs::BizData>> onBusiness(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::fbs::BizData, ::fbs::BizData>>(onBusinessRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::fbs::BizData, ::fbs::BizData>> AsynconBusiness(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::fbs::BizData, ::fbs::BizData>>(AsynconBusinessRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::fbs::BizData, ::fbs::BizData>> PrepareAsynconBusiness(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::fbs::BizData, ::fbs::BizData>>(PrepareAsynconBusinessRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::fbs::BizData, ::fbs::BizData>* onBusinessRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::fbs::BizData, ::fbs::BizData>* AsynconBusinessRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::fbs::BizData, ::fbs::BizData>* PrepareAsynconBusinessRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::fbs::BizData, ::fbs::BizData>> onBusiness(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::fbs::BizData, ::fbs::BizData>>(onBusinessRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::fbs::BizData, ::fbs::BizData>> AsynconBusiness(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::fbs::BizData, ::fbs::BizData>>(AsynconBusinessRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::fbs::BizData, ::fbs::BizData>> PrepareAsynconBusiness(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::fbs::BizData, ::fbs::BizData>>(PrepareAsynconBusinessRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::fbs::BizData, ::fbs::BizData>* onBusinessRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::fbs::BizData, ::fbs::BizData>* AsynconBusinessRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::fbs::BizData, ::fbs::BizData>* PrepareAsynconBusinessRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_onBusiness_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status onBusiness(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::fbs::BizData, ::fbs::BizData>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_onBusiness : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_onBusiness() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_onBusiness() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status onBusiness(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::fbs::BizData, ::fbs::BizData>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestonBusiness(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::fbs::BizData, ::fbs::BizData>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_onBusiness<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_onBusiness : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_onBusiness() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_onBusiness() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status onBusiness(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::fbs::BizData, ::fbs::BizData>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_onBusiness : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_onBusiness() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_onBusiness() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status onBusiness(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::fbs::BizData, ::fbs::BizData>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestonBusiness(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace fbs


#endif  // GRPC_fbs_2eproto__INCLUDED
