// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fbs.proto

#ifndef PROTOBUF_INCLUDED_fbs_2eproto
#define PROTOBUF_INCLUDED_fbs_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_fbs_2eproto 

namespace protobuf_fbs_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_fbs_2eproto
namespace fbs {
class BizData;
class BizDataDefaultTypeInternal;
extern BizDataDefaultTypeInternal _BizData_default_instance_;
}  // namespace fbs
namespace google {
namespace protobuf {
template<> ::fbs::BizData* Arena::CreateMaybeMessage<::fbs::BizData>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace fbs {

// ===================================================================

class BizData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fbs.BizData) */ {
 public:
  BizData();
  virtual ~BizData();

  BizData(const BizData& from);

  inline BizData& operator=(const BizData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BizData(BizData&& from) noexcept
    : BizData() {
    *this = ::std::move(from);
  }

  inline BizData& operator=(BizData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BizData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BizData* internal_default_instance() {
    return reinterpret_cast<const BizData*>(
               &_BizData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BizData* other);
  friend void swap(BizData& a, BizData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BizData* New() const final {
    return CreateMaybeMessage<BizData>(NULL);
  }

  BizData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BizData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BizData& from);
  void MergeFrom(const BizData& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BizData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes byteData = 1;
  void clear_bytedata();
  static const int kByteDataFieldNumber = 1;
  const ::std::string& bytedata() const;
  void set_bytedata(const ::std::string& value);
  #if LANG_CXX11
  void set_bytedata(::std::string&& value);
  #endif
  void set_bytedata(const char* value);
  void set_bytedata(const void* value, size_t size);
  ::std::string* mutable_bytedata();
  ::std::string* release_bytedata();
  void set_allocated_bytedata(::std::string* bytedata);

  // @@protoc_insertion_point(class_scope:fbs.BizData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr bytedata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_fbs_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BizData

// bytes byteData = 1;
inline void BizData::clear_bytedata() {
  bytedata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BizData::bytedata() const {
  // @@protoc_insertion_point(field_get:fbs.BizData.byteData)
  return bytedata_.GetNoArena();
}
inline void BizData::set_bytedata(const ::std::string& value) {
  
  bytedata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fbs.BizData.byteData)
}
#if LANG_CXX11
inline void BizData::set_bytedata(::std::string&& value) {
  
  bytedata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fbs.BizData.byteData)
}
#endif
inline void BizData::set_bytedata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  bytedata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fbs.BizData.byteData)
}
inline void BizData::set_bytedata(const void* value, size_t size) {
  
  bytedata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fbs.BizData.byteData)
}
inline ::std::string* BizData::mutable_bytedata() {
  
  // @@protoc_insertion_point(field_mutable:fbs.BizData.byteData)
  return bytedata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BizData::release_bytedata() {
  // @@protoc_insertion_point(field_release:fbs.BizData.byteData)
  
  return bytedata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BizData::set_allocated_bytedata(::std::string* bytedata) {
  if (bytedata != NULL) {
    
  } else {
    
  }
  bytedata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bytedata);
  // @@protoc_insertion_point(field_set_allocated:fbs.BizData.byteData)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace fbs

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_fbs_2eproto
